wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688779093.353941
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 5
