name: Deploy to Render

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to Render
        uses: renderlabs/github-action@1.7.1
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          render.yaml: ./.render.yaml
